version: "3.0"

services:
  memcached:
    image: 947039910131.dkr.ecr.us-east-1.amazonaws.com/yopass:latest
    restart: always
    expose:
      - "11211"

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - "127.0.0.1:80:80"
    command: "--memcached=memcached:11211 --port 80"
